[IV-23-24] - Objetivo 0
AlvaroSanPal95/AssignedOrganization pull request #1
Opened 2023-10-03 16:15 UTC by AlvaroSanPal95

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-10-03 18:32 UTC, JJ requested changes
Gracias por enviarlo, pero habría que hacer un esfuerzo adicional por superar el objetivo. La metodología de *design thinking*, que es la que se debe usar en este objetivo, te pide *empatizar* con este amigo para poder averiguar qué problemas podrían ser adecuados para esta asignatura; pero por favor, lo más importante es que tengas en cuenta esto, que son problemas que tendrás que desarrollar en esta asignatura. Si tú mismo no formulas claramente el problema, ni lo entiendes, ni tienes datos, ni sabes si serás capaz de programarlo por ti mismo sin recurrir a ningún API o biblioteca externa, *no sería un problema adecuado para la asignatura*.

Lee sobre esa metodología de *design thinking* y mira a ver qué sería lo más adecuado, que en todo caso pasa por hablar con esa persona y ver a qué problemas se enfrenta (y sobre los cuales tiene datos), problemas que, si tienen la complejidad correcta (ni demasiado complejos para que haya que aplicar APIs externas o machine learning ni demasiado simples para que se resuelvan con una aplicación aritmética) pueden ser un buen proyecto que te permita llevar esta asignatura a término.

2023-10-03 18:32 UTC, JJ commented on README.md
> +La idea es calcular una ruta optimizada analizando los datos disponibles, pudiendo predecir un mayor beneficio económico.
Tienes que limitarte a plantear un problema. La solución sólo debe explicarse si no está claro que genere un problema adecuado para tratarlo en la asignatura.

2023-10-03 18:32 UTC, JJ commented on README.md
> +Un amigo con atracciones de feria, tiene el problema de no saber a que pueblos ir, de forma que no esté viajando demás y que pueda maximizar beneficios.
Del [documento sobre equivocaciones frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-0.md):

> Crear problemas demasiado vagos ("una persona quiere invertir") o simplemente descritos como tales ("el problema del transporte").

En tu caso, "el problema de no saber a qué pueblos ir"

2023-10-05 16:50 UTC, AlvaroSanPal95 commented on README.md
> +Un amigo con atracciones de feria, tiene el problema de no saber a que pueblos ir, de forma que no esté viajando demás y que pueda maximizar beneficios.
Buenas @JJ una duda antes de darle una vuelta al problema:

No se permite la utilización de APIs externas para obtener algún tipo de dato?
En el caso de mi problema, había pensado como una posible solución, usar algunos datos públicos, así como un método en php que hace uso de una API externa, a la que le pasaría ciertos datos.

En caso de no poder utilizarla, quizás debería pensar en otro problema más adecuado.

Muchas gracias por su atención!

2023-10-05 17:05 UTC, AlvaroSanPal95 commented
Buenas @JJ una duda antes de darle una vuelta al problema:

No se permite la utilización de APIs externas para obtener algún tipo de dato?
En el caso de mi problema, había pensado como una posible solución, usar algunos datos públicos, así como un método en php que hace uso de una API externa, a la que le pasaría ciertos datos.

En caso de no poder utilizarla, quizás debería pensar en otro problema más adecuado.

Muchas gracias por su atención!

2023-10-05 17:49 UTC, JJ commented
> Buenas @JJ una duda antes de darle una vuelta al problema:
> 
> No se permite la utilización de APIs externas para obtener algún tipo de dato? En el caso de mi problema, había pensado como una posible solución, usar algunos datos públicos, así como un método en php que hace uso de una API externa, a la que le pasaría ciertos datos.

Me temo que no. Como dice [en el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio):

> El centrarnos en la lógica de negocio (extraer información del texto de una página web ya descargada, por ejemplo) en vez de en los aspectos mecánicos (cómo obtener el URL de la página y cómo descargársela) permite que nos centremos en lo esencial de nuestro programa, que es lo que añade valor al cliente (no el hecho de que uno se descargue una página, o extraiga información de un API o como sea).

Un poco más abajo, dice:

> De la misma forma, aplicaciones que tengan una dependencia externa fuerte (por ejemplo, que recojan datos de un API externo, que pidan una gran cantidad de datos al usuario o que simplemente integren una biblioteca externa para llevar a cabo una operación sobre datos también externos) tampoco van a ser buenos proyectos, porque sus pruebas van a ser complicadas y no van a incluir ningún tipo de modelo.

 
> En caso de no poder utilizarla, quizás debería pensar en otro problema más adecuado.

Como os he comentado, la idea principal es que apliquéis *design thinking*.  Si tenéis claro quién puede ser el cliente y tenéis acceso al mismo, llevar a cabo ese proceso os ayudará a identificar un problema o problemas que serían adecuados para continuar en esta asignatura.

2023-10-07 08:32 UTC, AlvaroSanPal95 commented
Buenos días @JJ ;
He cambiado de forma radical el problema, para que sea uno en el cual esté más implicado, y del que pueda obtener feedback  y aportar calidad de vida directamente a personas cercanas.

Cuando usted pueda, agradecería le echase un vistazo y me  diga si se ajusta a los objetivos de la asignatura.

En principio no he especificado nada de la solución, en caso necesario lo añado.

Muchas gracias nuevamente por su tiempo.

2023-10-07 08:33 UTC, AlvaroSanPal95 commented
Comentar también que le he cambiado el nombre al repositorio, en principio creo que no hay problema con eso, pero si ve algo raro me dice y lo reviso, Gracias!

2023-10-07 08:58 UTC, JJ approved these changes
:+1: 
OK, voy a darlo por bueno, porque en principio es un problema de scheduling de tareas que puede tener suficiente complicación como para necesitar un algoritmo para hacerlo; dependerá, claro, de las tareas y de las restricciones que haya, así como la prioridad.

2023-10-07 09:01 UTC, AlvaroSanPal95 commented
Vale, pues si le parece bien, hago el merge de la rama hacia su proyecto y me pongo a trabajar en el Hito 1, que ya voy tarde
Las tareas tendrán su prioridad y sus restricciones claro, aunque me parecía que no era necesario especificarlo, en las historias de usuario escribiré todo lo necesario para que se entienda.
Lo dicho, hago este merge y me pongo a trabajar en el siguiente objetivo
Mil gracias!

2023-10-07 09:01 UTC, merged

2023-10-07 09:11 UTC, JJ commented
> Vale, pues si le parece bien, hago el merge de la rama hacia su proyecto y me pongo a trabajar en el Hito 1, que ya voy tarde Las tareas tendrán su prioridad y sus restricciones claro, aunque me parecía que no era necesario especificarlo, en las historias de usuario escribiré todo lo necesario para que se entienda. Lo dicho, hago este merge y me pongo a trabajar en el siguiente objetivo Mil gracias!

Sí, claro, conviene que te pongas a trabajar en el 1 lo antes posible.

2023-10-11 09:32 UTC, JJ commented
¿Cómo vas con el siguiente objetivo?